package userService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Users service. Represents a row in the &quot;UserServices_Users&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userService.model.impl.UsersModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userService.model.impl.UsersImpl}.
 * </p>
 *
 * @author Yevgen Kogut
 * @see Users
 * @see userService.model.impl.UsersImpl
 * @see userService.model.impl.UsersModelImpl
 * @generated
 */
public interface UsersModel extends BaseModel<Users> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a users model instance should use the {@link Users} interface instead.
     */

    /**
     * Returns the primary key of this users.
     *
     * @return the primary key of this users
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this users.
     *
     * @param primaryKey the primary key of this users
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the user ID of this users.
     *
     * @return the user ID of this users
     */
    public long getUserId();

    /**
     * Sets the user ID of this users.
     *
     * @param userId the user ID of this users
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this users.
     *
     * @return the user uuid of this users
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this users.
     *
     * @param userUuid the user uuid of this users
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this users.
     *
     * @return the user name of this users
     */
    @AutoEscape
    public String getUserName();

    /**
     * Sets the user name of this users.
     *
     * @param userName the user name of this users
     */
    public void setUserName(String userName);

    /**
     * Returns the email of this users.
     *
     * @return the email of this users
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this users.
     *
     * @param email the email of this users
     */
    public void setEmail(String email);

    /**
     * Returns the text of this users.
     *
     * @return the text of this users
     */
    @AutoEscape
    public String getText();

    /**
     * Sets the text of this users.
     *
     * @param text the text of this users
     */
    public void setText(String text);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Users users);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Users> toCacheModel();

    @Override
    public Users toEscapedModel();

    @Override
    public Users toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
